# Sample Streamlit secrets file
# Rename this file to secrets.toml and place it in the .streamlit directory
# Replace the placeholder values with your actual secrets

GOOGLE_API_KEY = "your-google-api-key-here"
SENDER_EMAIL = "your-email@example.com"
SENDER_EMAIL_PASSWORD = "your-email-app-password"

POSTGRES_HOST = "localhost"
POSTGRES_PORT = 5432
POSTGRES_DB = "gigsdb"
POSTGRES_USER = "asifullah"
POSTGRES_PASSWORD = "password1122"
